# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tweet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tweet
  pod 'Floaty'

  target 'TweetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TweetUITests' do
    # Pods for testing
  end

end
